### ISSUE TITLE
tensorboard.plugins.hparams error

### ISSUE THREAD

**Issue by HninPannPhyu** [babaniyi/deep_contextual_bandits#1]
I have followed below and obtained another error, “ TypeError: HParam.__init__() got an unexpected keyword argument 'num_actions'”

from tensorboard.plugins.hparams import api as hp

Then you can instantiate the parameters as:
hp.HParam(num_actions = num_actions)

**Comment by babaniyi** [comment]
Hello,
Since `tensorflow.contrib` was deprecated, i was hoping  `tensorboard.plugins.hparams` would work seamlessly but it seems there are subtleties.
I will be working on converting this project to be compatible with Tensorflow 2.X next month in addition to other commitment I made to convert it to a python package.

For a start, I will suggest you use downgrade your tensorflow to 1.13.

**Comment by babaniyi** [comment]
@HninPannPhyu ,

You may also consider the package below that uses that was built upon this.
https://github.com/mlisicki/NeuralKernelBandits

**Comment by HninPannPhyu** [comment]
@babaniyi Thanks for your response and i will look into those alternatives you provided.
